Supersim
wevm/prool pull request #29
Opened 2024-10-02 17:18 UTC by nitaliano

* Adds instance type for [supersim](https://github.com/ethereum-optimism/supersim)
* Update CI to install the latest version of `supersim` from it gh releases

2024-10-06 05:48 UTC, jxom commented
Is this ready for review?

2024-10-06 16:21 UTC, nitaliano commented
@jxom the `supersim` instance is good to go and is working for me locally. One thing I'm still working through and it could always be in a different PR is how to handle the proxy in front of supersim. Since supersim is really just starting multiple anvil instances under the hood the proxy needs to be able to route the requests to the correct instance since multiple ports are being opened.

2025-03-20 14:05 UTC, leovigna commented
This would be super helpful for devs working on Superchain Interop!

2025-04-16 18:57 UTC, zainbacchus commented
For unit tests that rely on Interop

2025-04-24 14:48 UTC, tmm-test requested changes
haven't tried it out yet. just some code style feedback.

2025-04-24 14:48 UTC, tmm-test commented on src/instances/supersim.ts
> +  host?: string
```suggestion
  host?: string | undefined
```

2025-04-24 14:48 UTC, tmm-test commented on src/instances/supersim.ts
> +  l1Port?: number
```suggestion
  l1Port?: number | undefined
```

2025-04-24 14:48 UTC, tmm-test commented on src/instances/supersim.ts
> +  l2StartingPort?: number
```suggestion
  l2StartingPort?: number | undefined
```

2025-04-24 14:48 UTC, tmm-test commented on src/instances/supersim.ts
> +  }
```suggestion
  fork?: {
    /** L1 height to fork the superchain (bounds L2 time). `0` for latest */
    l1ForkHeight?: number | undefined

    /** chains to fork in the superchain, example mainnet options: [base, lyra, metal, mode, op, orderly, race, tbn, zora] */
    chains: string[]

    /** superchain network. example options: mainnet, sepolia, sepolia-dev-0 */
    network?: string | undefined
  } | undefined
```

2025-04-24 14:48 UTC, tmm-test commented on src/instances/supersim.ts
> +  }
```suggestion
  interop?: {
    /** Automatically relay messages sent to the L2ToL2CrossDomainMessenger using account 0xa0Ee7A142d267C1f36714E4a8F75612F20a79720 */
    autorelay?: boolean | undefined
  } | undefined
```

2025-04-24 14:48 UTC, tmm-test commented on src/instances/supersim.ts
> +const DEFAULT_PORT = 8545
Let's inline these below

2025-04-24 15:02 UTC, nitaliano commented
I'm going to close this out, I have my doubts this will even work at this point since it hasn't kept up with the updates to supersim. I don't work at OP Labs any longer and would probably be best for someone else to pick this up and get working.

2025-04-24 15:02 UTC, closed without merging